
<?php echo $this->getContent(); ?>

<?php echo $this->tag->form("data_ongkir/save") ?>

<table width="100%">
    <tr>
        <td align="left"><?php echo $this->tag->linkTo(array("data_ongkir", "Back")) ?></td>
        <td align="right"><?php echo $this->tag->submitButton("Save") ?></td>
    </tr>
</table>

<div align="center">
    <h1>Edit data_ongkir</h1>
</div>

<table>
    <tr>
        <td align="right">
            <label for="nama_daerah">nama_daerah</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("nama_daerah", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="ongkir">ongkir</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("ongkir", "size" => 30)) ?>
        </td>
    </tr>
   
    <tr>
        <td><?php echo $this->tag->hiddenField("_id") ?></td>
        <td><?php echo $this->tag->submitButton("Save") ?></td>
    </tr>
</table>

</form>
