
<?php echo $this->getContent() ?>

<div align="right">
    <?php echo $this->tag->linkTo(array("data_ongkir/new", "Create data_ongkir")) ?>
</div>

<?php echo $this->tag->form(array("data_ongkir/search", "autocomplete" => "off")) ?>

<div align="center">
    <h1>Search data_ongkir</h1>
</div>

<table>
    <tr>
        <td align="right">
            <label for="nama_daerah">Nama</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("nama_daerah", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="ongkir">ongkir</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("ongkir", "size" => 30)) ?>
        </td>
    </tr>
    
    <tr>
        <td></td>
        <td><?php echo $this->tag->submitButton("Search") ?></td>
    </tr>
</table>

</form>
