
<?php echo $this->tag->form("data_ongkir/create") ?>

<table width="100%">
    <tr>
        <td align="left"><?php echo $this->tag->linkTo(array("data_ongkir", "Go Back")) ?></td>
        <td align="right"><?php echo $this->tag->submitButton("Save") ?></td>
    </tr>
</table>

<?php echo $this->getContent(); ?>

<div align="center">
    <h1>Create data_ongkir</h1>
</div>

<table>
    <tr>
        <td align="right">
            <label for="nama_daerah">Nama</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("nama_daerah", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="ongkir">ongkir</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("ongkir", "size" => 30)) ?>
        </td>
    </tr>
    
    <tr>
        <td></td>
        <td><?php echo $this->tag->submitButton("Save") ?></td>
    </tr>
</table>

</form>
